import Field from '../../../types/field';
import { STATUS_UC_OPTIONS } from '../options';
export const ReadingCreateFields: Field[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    value: '',
    rowGroup: '0',
    isRequired: true,
    colSpan: 12,
  },
  {
    name: 'category_id',
    label: 'Category',
    type: 'select',
    value: null,
    isRequired: true,
    colSpan: 12,
    rowGroup: '1',
    options: [],
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    value: '',
    isRequired: false,
    rowGroup: '2',
    colSpan: 12,
  },
  {
    name: 'reference',
    label: 'Reference',
    type: 'text',
    value: '',
    rowGroup: '2',
    isRequired: false,
    colSpan: 12,
  },
  {
    name: 'is_active',
    label: 'Status',
    isRequired: true,
    type: 'select',
    value: STATUS_UC_OPTIONS[0].value,
    rowGroup: '3',
    colSpan: 6,
    options: STATUS_UC_OPTIONS,
  },
  {
    name: 'file',
    label: 'Video File',
    type: 'file',
    isRequired: true,
    value: '',
    rowGroup: '6',
    colSpan: 12,
    fileAccept: 'video/*',
  },
  {
    name: 'image',
    label: 'Image',
    type: 'file',
    value: '',
    rowGroup: '7',
    isRequired: true,
    colSpan: 12,
  },
];
