import Field from '../../../types/field';
import { DIFFICULTY_OPTIONS_UC, STATUS_UC_OPTIONS } from '../options';

export const ReadingEditFields: Field[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    value: '',
    rowGroup: '0',
    isRequired: true,
    colSpan: 12,
  },
  {
    name: 'category',
    label: 'Category',
    type: 'select',
    value: null,
    isRequired: true,
    colSpan: 12,
    rowGroup: '1',
    options: [],
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    value: '',
    isRequired: false,
    rowGroup: '2',
    colSpan: 12,
  },

  {
    name: 'reference',
    label: 'Reference',
    type: 'text',
    value: '',
    isRequired: false,
    rowGroup: '3',
    colSpan: 12,
  },
  {
    name: 'difficulty_level',
    label: 'Difficulty Level',
    type: 'select',
    value: 1,
    isRequired: true,
    colSpan: 12,
    rowGroup: '4',
    options: DIFFICULTY_OPTIONS_UC,
  },
  {
    name: 'is_active',
    label: 'Active?',
    type: 'select',
    value: '',
    isRequired: true,
    rowGroup: '5',
    colSpan: 12,
    options: STATUS_UC_OPTIONS,
  },
  {
    name: 'file',
    label: 'Video File',
    type: 'file',
    value: '',
    isRequired: true,
    rowGroup: '6',
    colSpan: 12,
    fileAccept: 'video/*',
  },
  {
    name: 'image',
    label: 'Image',
    type: 'file',
    value: '',
    isRequired: true,
    rowGroup: '7',
    colSpan: 12,
  },
];
