import Field from '@/types/field';

export const TeacherEditFields: Field[] = [
  {
    name: 'username',
    label: 'Username ',
    type: 'text',
    value: '',
    rowGroup: '1',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'name',
    label: 'Full Name ',
    type: 'text',
    value: '',
    rowGroup: '1',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'email',
    label: 'Email ',
    type: 'text',
    value: '',
    rowGroup: '2',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'phone',
    label: 'Phone',
    type: 'text',
    value: '',
    rowGroup: '2',
    colSpan: 6,
    isRequired: false,
  },
  {
    name: 'role_id',
    label: 'Role ',
    type: 'select',
    value: '',
    rowGroup: '3',
    colSpan: 6,
    isRequired: true,
    options: [],
  },
  {
    name: 'gender',
    label: 'Gender',
    type: 'select',
    value: '',
    rowGroup: '4',
    colSpan: 6,
    isRequired: false,
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'dob',
    label: 'Date of Birth',
    type: 'date',
    value: '',
    rowGroup: '4',
    colSpan: 6,
    isRequired: false,
  },
  {
    name: 'status',
    camelName: 'status',
    label: 'Status',
    type: 'select',
    value: '',
    rowGroup: '3',
    colSpan: 6,
    isRequired: true,
    options: [
      { label: 'Kích hoạt', value: 1 },
      { label: 'Vô hiệu hóa', value: 0 },
    ],
  },
];
