import Field from '../../../types/field';

export const UserEditFields: Field[] = [
  {
    name: 'email',
    camelName: 'email',
    label: 'Email',
    type: 'text',
    value: '',
    rowGroup: '1',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'username',
    camelName: 'username',
    label: 'Username',
    type: 'text',
    value: '',
    rowGroup: '1',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'name',
    camelName: 'name',
    label: 'Display Name',
    type: 'text',
    value: '',
    rowGroup: '2',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'phone',
    camelName: 'phone',
    label: 'Phone number',
    type: 'text',
    value: '',
    rowGroup: '2',
    colSpan: 6,
  },
  {
    name: 'dob',
    camelName: 'dob',
    label: 'Date of Birth',
    type: 'date',
    value: '',
    rowGroup: '3',
    colSpan: 6,
  },
  {
    name: 'gender',
    camelName: 'gender',
    label: 'Gender',
    type: 'select',
    value: '',
    rowGroup: '3',
    colSpan: 6,
    isRequired: true,
    options: [
      { label: 'Male', value: 'male' },
      { label: 'Female', value: 'female' },
    ],
  },
  {
    name: 'role_id',
    camelName: 'role_id',
    label: 'Select Role',
    type: 'select',
    value: '',
    rowGroup: '4',
    colSpan: 6,
    isRequired: true,
  },
  {
    name: 'status',
    camelName: 'status',
    label: 'Status',
    type: 'select',
    value: '',
    rowGroup: '4',
    colSpan: 6,
    isRequired: true,
    options: [
      { label: 'Active', value: 1 },
      { label: 'Inactive', value: 0 },
    ],
  },
];
