export const ENDPOINT = {
  REVENUE: '/revenue',
  CASHFLOW: '/cash-flow',
  EMPLOYEE: '/entity-code',
  REVENUE_EXPENSE: '/revenue-expense',
  ACCOUNTING_ACCOUNT: '/accounting-account',
  ROLE: '/role',
  USER: '/user',
  DEBT: '/debt',
  VEHICLE: '/vehicle',
  TRANSFER_PLAN: '/transfer-plan',
  LEDGER: '/ledger',
  SCAN_DATA: '/scan-data',
  FUNCTION: '/function',
  TRIP: '/trip',
  STUDENT_REPORT: '/reports/student-report',
  READING: '/kid-reading',
  EBOOK: "/e-book",
  EBOOK_CATEGORY: "/e-book-category",
  EBOOK_CATEGORY_STATS: "/e-book-category/stats",
  READING_CATEGORY_STATS: "/reading-category/stats",
  READING_CATEGORY: "/reading-category",
  QUESTIONS: "/questions",
  STUDENT: "/kid-student",
  STUDENT_READING: "/student-reading",
  NOTIFY: '/notify',
  FEEDBACK: '/feedback',
  LEARNING_PATH: '/learning-path',
  LEARNING_PATH_ADD_ITEMS: '/learning-path/:pathId/add-items',
  LEARNING_PATH_REORDER_CATEGORIES: '/learning-path/:pathId/categories/reorder',
  LEARNING_PATH_REORDER_ITEMS: '/learning-path/:pathId/categories/:categoryId/items/reorder',

  // Reading category and available readings APIs
  READING_CATEGORY_LIST: '/reading-category/get-list-no-filter',
  CATEGORY_AVAILABLE_READINGS: `/kid-reading/:categoryId/available-readings`,
};
