export const ROUTES = {
  // Core Routes
  SIDEBAR: '/sidebar',
  HEADER: '/header',
  PROFILE: '/profile',
  DASHBOARD: '/dashboard',
  REVENUE: '/revenue',
  CASHFLOW: '/cash-flow',
  EMPLOYEE: '/employee',
  CUSTOMER: '/customer',
  ROLE: '/role',
  USER: '/user',
  TEACHER: '/teacher',
  VEHICLE: '/vehicle',
  DEBT: '/debt',
  TRANSFER_PLAN: '/transfer-plan',
  ACCOUNTING_ACCOUNT: '/accounting-account',
  ASSIGN_VEHICLE: '/assign-vehicle',
  ASSIGN_VEHICLE_HISTORY: '/assign-vehicle-history',
  REVENUE_EXPENSE: '/expense',
  LEDGER: '/ledger',
  LOGIN: '/',
  LOGIN2: '/login',
  FORGOTPASS: '/forgot-password',
  VERIFYCODE: '/verify-code',
  RESETPASS: '/reset-password',
  CHANGEPASS: '/change-password',
  FORBIDDEN: '/forbidden',
  NOT_FOUND: '*',
  ACCOUNTING_SETTLEMENT: '/accounting-settlement',
  SCAN_DATA: '/scan-data',
  CHOOSE_TRIP: '/choose-trip',
  SEARCH_INFORMATION: '/search-information',
  REPORT_BY_ACCOUNT: '/report-by-account',
  STUDENT_REPORT: '/student-report',
  READING: '/kid-reading',
  EBOOK: '/e-book',
  EBOOK_CATEGORY: '/e-book-category',
  EBOOK_CATEGORY_REPORT: '/e-book-category/report',
  READING_CATEGORY: '/reading-category',
  READING_CATEGORY_REPORT: '/reading-category/report',
  QUESTIONS: '/kid-reading/:id/questions',
  EDIT_QUESTION: '/kid-reading/:kid_reading_id/questions/:id/edit',
  CREATE_QUESTION: '/kid-reading/:kid_reading_id/questions/create',
  STUDENT: '/student',
  DETAIL_STUDENT: '/student/:id',
  STUDENT_STATISTICS: '/student/:id/statistics',
  NOTIFICATION: '/notification',
  CREATE_NOTIFICATION: '/notification/create',
  EDIT_NOTIFICATION: '/notification/:id/edit',
  FEEDBACK_ADMIN: '/feedback-admin',
  FEEDBACK_ADMIN_DETAIL: '/feedback-admin/:id',
  FEEDBACK_TEACHER: '/feedback-teacher',
  FEEDBACK_TEACHER_DETAIL: '/feedback-teacher/:id',
  LEARNING_PATH: '/learning-path',
  EDIT_LEARNING_PATH: '/learning-path/:id/edit',
  EDIT_ITEMS_LEARNING_PATH: '/learning-path/:id/items',
  
  // Game Management Routes
  GAMES: '/games',
  GAMES_BY_READING: '/kid-reading/:id/games',
  CREATE_GAME: '/kid-reading/:id/games/create',
  EDIT_GAME: '/kid-reading/:id/games/:gameId/edit',
  EDIT_GAME_GENERAL: '/games/:gameId/edit',

  // Word Management Routes
  WORDS: '/word',
  CREATE_WORD: '/word/',
  ASSIGN_WORDS: '/word/game/:gameId/words',
};
